# Generated by Django 4.2.27 on 2026-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='id_produk',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
